# Generated by Django 4.1.5 on 2023-01-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
